### ISSUE TITLE
armhf vs arm64

### ISSUE THREAD

**Issue by DrewKnowles1** [mattogodoy/omni#3]
Hey, This is really cool - thanks for all the hard work :smile:

Just thought I'd raise this, as it was a small issue I hit.

my hardware:

1 x raspberry pi 4 (8gb)
2 x raspberry pi 3b+ 's (1gb)
7 x raspberry pi compute module 3+'s (1gb)
All running ubuntu server 20.04 LTS **64-bit**

On trying to install using your Ansible, i got this error across all nodes:

`fatal: [node2]: FAILED! => {"changed": true, "cmd": ["dpkg", "-i", "libseccomp2_2.5.1-1_armhf.deb"], "delta": "0:00:00.237499", "end": "2021-06-18 14:07:28.893279", "msg": "non-zero return code", "rc": 1, "start": "2021-06-18 14:07:28.655780", "stderr": "dpkg: error processing archive libseccomp2_2.5.1-1_armhf.deb (--install):\n package architecture (armhf) does not match system (arm64)\nErrors were encountered while processing:\n libseccomp2_2.5.1-1_armhf.deb", "stderr_lines": ["dpkg: error processing archive libseccomp2_2.5.1-1_armhf.deb (--install):", " package architecture (armhf) does not match system (arm64)", "Errors were encountered while processing:", " libseccomp2_2.5.1-1_armhf.deb"], "stdout": "", "stdout_lines": []}`

I just switched the URL to point to an arm64 binary instead and all was fine.
I was going to make the change and open a pull request, but i appreciate you may want to keep the current armhf deb in place for a number of reasons! If not, let me know and I'll get a pull request opened!

For anyone who may come across this issue in future, my fix was updating the ansible-playbook-libs.yaml file to the following:
 
      - name: Download libseccomp2.deb
        command: "wget http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.1-1_arm64.deb"
        become: yes

      - name: Install libseccomp2.deb
        command: "dpkg -i libseccomp2_2.5.1-1_arm64.deb"
        become: yes`

Thanks again!

**Comment by mattogodoy** [comment]
Thank you!

You are correct. This happens because I'm using the 32-bit version of Raspbian.
Even though I'm planning to update to 64-bit soon, I think the best way to go should be to have both options. Maybe an Ansible playbook for 32 and another one for 64. Using the same playbook but setting a variable first could be another option.
Or maybe even detecting it automatically for every host.

Any ideas are welcome :)

**Comment by mattogodoy** [comment]
In the meantime I just updated the [README](https://github.com/mattogodoy/omni/blob/master/README.md) file and added a note linking to this issue.

**Comment by slaecker** [comment]
Just for information in case somebody else stumbles upon this.

On Ubuntu Server 20.04 you can just install it via apt.

In my case it was already installed:

```
sudo apt update
sudo apt install libseccomp2                                                                                                                                                 slaecker@pinas   09:30:42
Reading package lists... Done
Building dependency tree
Reading state information... Done
libseccomp2 is already the newest version (2.5.1-1ubuntu1~20.04.2).
libseccomp2 set to manually installed.
```
